spring.application.name=core-service
server.port=${PORT:8080}

# Database Configuration with dynamic support for local and Railway variables
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:aifitness}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${MYSQLUSER:${SPRING_DATASOURCE_USERNAME:root}}
spring.datasource.password=${MYSQLPASSWORD:${SPRING_DATASOURCE_PASSWORD:1234}}

# JPA and Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



